documentation:
- all: [./**/*.md']

test:
- all: ['./**/*.spec.js']

dependencies
- all: ['./**/package.json']

frontend:
- any: ['src/**/*.js', 'src/**/*.svelte']
  all: ['!./**/src/server.js']

backend:
- any: ['./**/*.js', './**/*.json', './**/src/server.js']
  all: ['!/**/*.svelte']
