backend:
  - any: ['*/**/*.js', '*/**/*.json', 'src/server.js']
    all: ['!src/**/*.js']

documentation:
  - all: ['*/**/*.md']

test:
  - all: ['*/**/*.spec.js']

frontend:
- any: ['src/**/*.js', 'src/**/*.svelte']
  all: ['!src/server.js']
