backend:
  - any: ['./**/*.js', 'src/server.js']
  - all: ['!src/**/*.js']

documentation
  - any: ['./**/*.md']

test:
  - cypress/**/*.spec.js

frontend:
- any: ['src/**/*.js', 'src/**/*.svelte']
  all: ['!src/server.js']
