name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cache
            !~/.cache/exclude
            !~/.exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node }}
      - run: npm i && npm run export
