name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ 14.x ]
        os: [ ubuntu-latest, windows-latest ] # ubuntu-latest, macos-latest, windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@master
        with:
          path: |
            ~/.cache
            !~/.cache/exclude
            ~/.static
            !~/.exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm run export
      - run: npm run static
      - run: ps aux | grep -i node | awk '{print $2}' | xargs
