name: cypress

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ 14.5.x ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{ github.token }}
      - uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cache
            **/node_modules
            **/static
            **/__sapper__/export
            !~/.cache/exclude
            !~/.exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node }}
      - run: npm i && npm run test
        env:
            CI: true
            PORT: 5000
            NODE_ENV: production
            # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
        with:
          chromedriver-version: '77.0.3865.40'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: ./
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshots-chrome
          path: cypress/screenshots/chrome
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: videos-chrome
          path: cypress/videos/chrome
      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: ./
      - run: ffprobe cypress/videos/*.mp4 || true
      - run: mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true
