name: cypress

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ 10, 12, 14 ]
        os: [ ubuntu-latest ] # keys: ubuntu-latest,macos-latest,windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@master
        with:
          path: |
            ~/.cache
            !~/.cache/exclude
            ~/.static
            !~/.exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm run test
        env:
            CI: true
            # or something else, like: CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@master
        # with:
        #   chromedriver-version: '84.0.4147.30'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1920x1080x32 > /dev/null 2>&1 & # optional
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: ./
      - name: upload chrome-screenshots
        uses: actions/upload-artifact@master
        with:
          name: screenshots-chrome
          path: cypress/screenshots/chrome
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: upload chrome-videos
          path: cypress/videos/chrome
      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: ./
      - run: ffprobe cypress/videos/*.mp4 || true
      - run: mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true
