name: cypress

on: [ push, pull_request ]

jobs:

  cypress-run:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [ 14.5.x ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    name: Cypress run
    steps:
    - name: Running on ${{ matrix.os }} with node@v${{ matrix.node }}
      uses: cypress-io/github-action@v2
      with:
        record: true
        tag: node-${{ matrix.node }}
      env:
        CI: true
        PORT: 5000
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
